### ISSUE TITLE
[Minor Issue] Interesting mod-multiblock interaction

### ISSUE THREAD

**Issue by accessdenied0** [KidsDontPlay/Tools#7]
Hello Mr. Riegel. 

I guess this is more of a minor issue but I report it anyway:
I tired to break a formed Blastfurnus structure from Immersive Engineering with a Flexible Pickaxe (Energy Upgrade, Mending, 3x3 Mining). And because of the 3x3 Mining [it dropped an additional Item it shouldn't drop for sure.](http://puu.sh/wXQeS/c015642abf.png)

Maybe you can fix it if you want to, but I guess it is not that gamebreaking (?!?)

access_denied

**Comment by KidsDontPlay** [comment]
@blusunrize

`getDrops(NonNullList<ItemStack> drops, IBlockAccess world, BlockPos pos, IBlockState state, int fortune)` delivers a list with that Crude Blast Furnace Item.

`getDrops(IBlockAccess world, BlockPos pos, IBlockState state, int fortune)` returns an empty list.

I use the first one to get the drops because the latter is deprecated.

**Comment by BluSunrize** [comment]
Is this 1.12?
I don't think the deprecation marker was present in 1.10.

Anyway, file an issue on my tracker, I'll deal with it in like 2 weeks when I get back from holidays.
